POST  http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username":"ananhpv",
    "password":"ananhpv"
}

###

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username":"hung",
    "password":"hung123"
}

###

POST http://localhost:5000/api/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzM5Njg1MzRkYTViN2NiZWIwZmM0ZjYiLCJpYXQiOjE2NjQ3MDY2NDN9.RsSD0Pa26yDTYRWplDiXCCMOKyzJNF6PqBWLImhKy8E

{
    "description": "I want to learn React",
    "title": "React"
}